### ISSUE TITLE
No tests using equals

### ISSUE THREAD

**Issue by kylesferrazza** [grahamwren/cs4500-assignment_1-part2#4]
All of your tests seem to use `==`, checking that the object that was put in is the object that comes out.

This may be up to the implementation - while the `String` that comes out should definitely be equal (with `equals`) to the `String` that was put in, it does not necessarily have to be the same exact instance of `String` (with `==`).

**Comment by grahamwren** [comment]
The returned `Strings` **must** be referentially equal to the strings which were inserted into the `Map`. Otherwise, the returned strings would have to be freed by the caller. Methods that allocate memory and return it **should** be very clearly distinguished and documented to avoid memory leaks. Since there is no documentation on our interface indicating that internally allocate memory will be returned, the implementation **must** not do this.

**Comment by grahamwren** [comment]
Additionally, this is further specified in the class comment for `Map`:

> All keys and values are owned by the caller, and none of the map's methods will modify them.

https://github.com/grahamwren/cs4500-assignment_1-part2/blob/4acbcd18ec1825596ae3dc0924379407beaa238a/map.h#L8-L14

**Comment by kylesferrazza** [comment]
Understood.
This means the tests must be updated to `delete` all of the strings they create when testing the map is over.
You also need to `delete` the `Map` itself.

**Comment by jagen31** [comment]
These allocations only happen once, so we don't care about cleaning them up.
